CINT-68 Add primary_identifier to JSON schema
brace-ai/schemas pull request #17
Opened 2021-01-23 15:13 UTC by kewpiedoll99

See https://bracesoftware.atlassian.net/browse/CINT-68

Borrower-api post-sso data callback needs to pass the `primary_identifier` to Servicer-api, but not as the `unique_borrower_identifier` (aka "UBI", which will be a different formulation - see {borrower work ticket}). there's no really good field in the schema for it yet so we decided to add `primary_identifier` in the `borrower` object. 

Make the field optional; atm only Flagstar will be using it.

2021-01-23 21:26 UTC, MSGoodman commented
I don't _entirely_ follow the context for this addition, but it seems pretty simple and straightforward so I'll trust your judgment 👍

2021-01-24 18:09 UTC, MSGoodman requested changes
One rather minor quibble regarding the version number, see comments

2021-01-25 17:11 UTC, kewpiedoll99 commented on json/v2.0.13/brace-data-exchange.schema.json
> +  "$id": "https://brace-ai.github.io/schemas/json/v2.0.12/brace-data-exchange.schema.json",
yes, thanks! my bad, good catch @MSGoodman !

2021-01-25 17:17 UTC, MSGoodman approved these changes

2021-01-25 17:19 UTC, merged